# prompts.py
# Contains only dico_styles for style prompts

dico_styles = {
    "clay":  "Transform this person into a claymation character. Give them a handcrafted look with soft, rounded features, visible fingerprints or texture in the clay, and slightly exaggerated expressions. Use stop-motion lighting and a warm, tactile feel. Background should look like a miniature set made of clay or craft materials.",
    "comic": "Turn this person into a bold comic book style character. Use clean black ink outlines, vibrant cel-shading, and dramatic contrast. Emphasize comic-style features like expressive eyes, stylized hair, and sharp facial structure. Keep the background minimal or graphic, like in classic comic panels",
    "oil paint": "Render the subject as a classical Renaissance oil painting. Preserve their exact identity, age, and gender, and depict them with high-contrast lighting emerging from a deep, shadowed background. Use smooth, yet expressive brushwork with rich pigment layering, especially in illuminated areas. The composition should be formal, dignified, and naturalistic, with refined anatomy and soft, golden light reminiscent of masters like Rembrandt, Caravaggio, or Leonardo da Vinci. Surround the figure with minimal, period-authentic detail or drapery, avoiding modern or fantastical elements. Textures should reflect aged canvas and layered oil paint, with subtle impasto highlights. Skin tones should be warm and realistic, set against velvety dark shadows. (renaissance painting: 1.1), (clair-obscur: 1.1), (oil painting: 1.1), (visible brushstrokes: 1.5), (pigment texture: 1.1), (impasto highlights: 1.5), (deep shadows: 1.1), (dramatic lighting: 1.1), (canvas texture: 1.1), (moody atmosphere: 1.1), (rich pigments: 1.5), (golden tones: 1.1)",
    "statue" : "Make it into a marble statue while preserving their original identity, age, and gender exactly. Sculpt them in smooth, white marble with realistic but modest features. Avoid any exaggeration or changes to body shape or facial structure. The statue should resemble classical art with respectful, child-appropriate detail. Use soft lighting and natural stone texture, with no added accessories or fantasy elements. Make sure the whole statue is white without colors. Make the eyes white, no black details. Lapis blue stones mosaics, gold metal engravings, green jade stones, obsidian glass tiles. (White eyes: 1.1), (White hair: 1.1), (clothes: 1.1), (white marble statue: 1.1)",
    #"stone" : "Transform this person into a stone statue, maintaining their original identity, age, and gender exactly. Sculpt them in rough, gray stone with realistic but modest features. Avoid any exaggeration or changes to body shape or facial structure. The statue should resemble classical art with respectful, child-appropriate detail. Use soft lighting and natural stone texture, with no added accessories or fantasy elements.",
    #"cyberpunk": "Transform this person into a futuristic cyberpunk character. Use neon colors, high-tech accessories, and a gritty urban aesthetic. Emphasize glowing elements like circuit patterns, holographic displays, and cybernetic enhancements. The background should be a dark, neon-lit cityscape with rain or fog for atmosphere.",
    #"retro": "Turn this person into a retro character from the 80s or 90s. Use bright, bold colors, geometric patterns, and nostalgic accessories like cassette tapes or vintage electronics. Emphasize a playful, vibrant style with exaggerated features. The background should reflect the era with neon lights, old-school technology, and a fun, upbeat atmosphere.",
    "steampunk": "Turn this person into a steampunk character with Victorian-era fashion and mechanical elements. Use brass, copper, and leather textures, with goggles, gears, and clockwork details. Emphasize a retro-futuristic look with intricate machinery and steam-powered accessories. The background should be an industrial setting with pipes, cogs, and vintage machinery.",
    #"fantasy": "Transform this person into a fantasy character with magical elements. Use vibrant colors, ethereal lighting, and whimsical accessories. Emphasize fantasy features like pointed ears, flowing hair, and mystical attire. The background should be a magical landscape with enchanted forests, castles, or mythical creatures.",
    #"history": "Transform this person into a historical figure from a specific era. Use period-appropriate clothing, hairstyles, and accessories. Emphasize the cultural and historical context of the time, whether it's ancient Rome, medieval Europe, or the Renaissance. The background should reflect the architecture and environment of that era, with attention to detail in the setting.",
    "minecraft": "Transform this person into a stylized Minecraft character, ensuring their original facial features, hairstyle, body type, and gender expression are clearly recognizable within the cubic, pixelated aesthetic of the Minecraft universe. Use blocky geometry to recreate the person's appearance, translating realistic details into simplified forms while retaining defining characteristics such as skin tone, hair color, hairstyle, facial structure, and clothing style. The Minecraft character should look as if it truly represents the individual, as though they were authentically rendered inside the game. Clothing should reflect the person’s usual outfit or fashion sense, reimagined with the classic 8-bit textures and limited color palettes typical of Minecraft skins. Accessories or unique style elements—such as glasses, jewelry, or hats—should be adapted in a pixel-friendly manner while still clearly referencing the real-world look. Maintain proportional accuracy according to Minecraft’s character format (e.g., square head, rectangular limbs), but ensure the transformed version still feels personal and identifiable. Place the character in a richly detailed Minecraft environment that complements their style or personality—this could be a lush forest biome, a cozy village, a castle setting, or any classic overworld scene. The background should include iconic blocky elements such as pixelated grass, trees, clouds, and structures made of wood, stone, or brick. Lighting should be bright and vivid, reflecting the cheerful tone of Minecraft’s visual style.",
    #"horror": "Transform this person into a horror character. Use dark colors, eerie lighting, and unsettling details. Emphasize horror elements like ghostly features, creepy accessories, and a menacing atmosphere. The background should be a dark, foreboding setting with elements like fog, shadows, and haunted structures.",
    #"cartoon": "Transform this person into a cartoon character. Use bright, bold colors, exaggerated features, and playful expressions. Emphasize cartoon-style elements like large eyes, simplified shapes, and whimsical accessories. The background should be colorful and fun, like a scene from a children's animated show.",
    "pixel art": "Transform this person into a pixel art character. Use a limited color palette, blocky shapes, and pixelated details. Emphasize the retro video game aesthetic with large, square pixels and simplified features. The background should be a pixelated landscape, like a classic 8-bit game scene.",
    #"watercolor": "Transform this person into a watercolor painting. Use soft, blended colors, and delicate brush strokes to create a dreamy, ethereal effect. Emphasize fluid shapes and a gentle color palette. The background should be a soft wash of color, like a blurred landscape or abstract design.",
    #"charcoal": "Transform this person into a charcoal drawing. Use bold, dark lines and soft shading to create a dramatic, textured effect. Emphasize the contrast between light and shadow, with a focus on the person's facial features and expressions. The background should be a simple, muted tone to highlight the charcoal texture.",
    #"sketch": "Transform this person into a pencil sketch. Use fine lines, shading, and cross-hatching to create a detailed, realistic effect. Emphasize the person's features with careful attention to detail, while keeping the overall look light and airy. The background should be a simple, untextured paper-like surface to enhance the sketch effect.",
    #"anime": "Transform this person into an anime character. Use vibrant colors, exaggerated facial features, and stylized hair. Emphasize large, expressive eyes, and a dynamic pose. The background should be a colorful, fantastical setting typical of anime, with elements like cherry blossoms, futuristic cityscapes, or magical landscapes.",
    "vintage": "Transform this person into a vintage character from the 1920s-1950s. Use sepia tones, classic hairstyles, and period-appropriate clothing. Emphasize a nostalgic, timeless look with soft lighting and a vintage aesthetic. The background should reflect the era with elements like old cars, vintage posters, or classic architecture.",
    #"roblox": "Transform this person into a Roblox character, ensuring their original facial features, hairstyle, body type, and gender expression are clearly recognizable within the blocky, pixelated aesthetic of the Roblox universe. Use simple shapes and bright colors to recreate the person's appearance, translating realistic details into a more cartoonish style while retaining defining characteristics such as skin tone, hair color, hairstyle, facial structure, and clothing style. The Roblox character should look as if it truly represents the individual, as though they were authentically rendered inside the game. Clothing should reflect the person’s usual outfit or fashion sense, reimagined with the classic Roblox textures and limited color palettes typical of Roblox avatars. Accessories or unique style elements—such as glasses, jewelry, or hats—should be adapted in a blocky manner while still clearly referencing the real-world look. Maintain proportional accuracy according to Roblox’s character format (e.g., blocky limbs, oversized head), but ensure the transformed version still feels personal and identifiable. Place the character in a richly detailed Roblox environment that complements their style or personality—this could be a vibrant cityscape, a cozy home, or any classic Roblox setting. The background should include iconic blocky elements such as pixelated grass, trees, clouds, and structures made of wood, stone, or brick. Lighting should be bright and vivid, reflecting the cheerful tone of Roblox’s visual style.",
    "disney": "Transform this person into a Disney-style character, ensuring their original facial features, hairstyle, body type, and gender expression are clearly recognizable within the whimsical, animated aesthetic of Disney films. Use soft lines and vibrant colors to recreate the person's appearance, translating realistic details into a more cartoonish style while retaining defining characteristics such as skin tone, hair color, hairstyle, facial structure, and clothing style. The Disney character should look as if it truly represents the individual, as though they were authentically rendered inside a Disney movie. Clothing should reflect the person’s usual outfit or fashion sense, reimagined with the classic Disney textures and limited color palettes typical of Disney characters. Accessories or unique style elements—such as glasses, jewelry, or hats—should be adapted in a playful manner while still clearly referencing the real-world look. Maintain proportional accuracy according to Disney’s character format (e.g., exaggerated features, large eyes), but ensure the transformed version still feels personal and identifiable. Place the character in a richly detailed Disney environment that complements their style or personality—this could be a magical kingdom, a bustling city, or any classic Disney setting. The background should include iconic elements such as lush landscapes, whimsical architecture, and enchanting details. Lighting should be bright and cheerful, reflecting the optimistic tone of Disney’s visual style."
}
